import { chromium } from "@playwright/test";
const b=await chromium.launch({headless:false,args:["--enable-gpu","--ignore-gpu-blocklist"]});
const c=await b.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1});
const p=await c.newPage();
await p.goto("http://localhost:4173/"); await p.waitForTimeout(4000);
await p.frameLocator("#nur-entry-stage").locator("body").evaluate(()=>window.nurShowFront?.());
await p.waitForTimeout(5000);
const e=p.frameLocator("#nur-entry-stage");
console.log("canvases:", JSON.stringify(await e.locator("body").evaluate(()=>
  [...document.querySelectorAll("canvas")].map(c=>({id:c.id||"(none)",w:c.width,h:c.height})))));
const fps=async(label)=>{const cdp=await p.context().newCDPSession(p);let f=0;const t0=Date.now();
  cdp.on("Page.screencastFrame",async({sessionId})=>{f++;try{await cdp.send("Page.screencastFrameAck",{sessionId});}catch{}});
  await cdp.send("Page.startScreencast",{format:"jpeg",quality:15,everyNthFrame:1});
  await p.waitForTimeout(4000); await cdp.send("Page.stopScreencast"); await cdp.detach();
  console.log(`${label.padEnd(32)} ${(f/((Date.now()-t0)/1000)).toFixed(1)} FPS`);};
await fps("baseline (all canvases)");
await e.locator("body").evaluate(()=>{const c=document.querySelector("#nur-brain-canvas"); if(c)c.style.display="none";});
await fps("brain hidden");
await e.locator("body").evaluate(()=>{const c=document.querySelector("#nur-brain-canvas"); if(c)c.style.display="";
  const s=document.querySelector("#space3d"); if(s)s.style.display="none";});
await fps("galaxy hidden");
await b.close();
