"""Test bootstrap: real PostgreSQL 16 + real Redis, no mocked persistence.

A fresh database (owner: nur_admin) is created per test run, the real Alembic
migrations are applied AS nur_admin, and the app connects AS nur_app
(NOBYPASSRLS) — exactly the production role split. Superuser access is used
only to provision the database and to assert on raw rows (superusers bypass
RLS; the app role never does).

RUN ISOLATION. Both the database name and the Redis keyspace are derived from a
per-run id, so two pytest invocations can execute against the same PostgreSQL
and Redis servers without touching each other. Previously both were fixed
(`nur_test`, plus a `flushdb` of Redis db 0), so a second concurrent run would
drop the first run's database and clear its rate-limit counters mid-test —
producing failures that look like product defects but are not. Set
NUR_TEST_RUN_ID to pin the id when a run must be reattached or debugged.
`test_run_isolation.py` is the regression proof."""
import asyncio
import os
import pathlib
import subprocess
import sys
import uuid

import pytest
import pytest_asyncio

API_DIR = pathlib.Path(__file__).resolve().parents[2]
# One id per pytest invocation. Every shared resource this run touches is keyed
# by it, so concurrent runs are invisible to each other.
RUN_ID = os.environ.setdefault("NUR_TEST_RUN_ID", uuid.uuid4().hex[:12])
TEST_DB = f"nur_test_{RUN_ID}"
REDIS_NAMESPACE = f"nurtest:{RUN_ID}"
ADMIN_PW, APP_PW = "test_admin_pw", "test_app_pw"

SUPER_DSN = os.environ.get("NUR_TEST_SUPERUSER_DSN",
                           "postgresql://postgres:postgres@localhost:5432/postgres")
_host = SUPER_DSN.split("@", 1)[1].split("/", 1)[0]
ADMIN_URL = f"postgresql+asyncpg://nur_admin:{ADMIN_PW}@{_host}/{TEST_DB}"
APP_URL = f"postgresql+asyncpg://nur_app:{APP_PW}@{_host}/{TEST_DB}"
SUPER_TEST_URL = SUPER_DSN.replace("postgresql://", "postgresql+asyncpg://").rsplit("/", 1)[0] + f"/{TEST_DB}"

os.environ.setdefault("REDIS_URL", "redis://localhost:6379/0")
os.environ["NUR_REDIS_KEY_NAMESPACE"] = REDIS_NAMESPACE
os.environ["APP_ENV"] = "development"
os.environ["NUR_AI_PROVIDER"] = "disabled"
os.environ["AI_PROVIDER"] = "disabled"
os.environ["DATABASE_URL"] = APP_URL
os.environ["ALEMBIC_DATABASE_URL"] = ADMIN_URL
# Deterministic AM Project runs execute in-process during tests (real adapter,
# real object storage, real bytes) — no external Celery worker required.
os.environ.setdefault("NUR_PROJECT_RUN_INLINE", "true")
# Keep uploaded/generated bytes inside an isolated per-run data root.
os.environ.setdefault(
    "NUR_PROJECT_OBJECT_ROOT",
    str(API_DIR / ".nur-runtime" / f"test-project-objects-{RUN_ID}"),
)


async def _drop_run_namespace() -> None:
    """Session teardown: remove this run's Redis keys instead of waiting for TTL."""
    from redis.asyncio import Redis
    redis = Redis.from_url(os.environ["REDIS_URL"], decode_responses=True)
    try:
        await clear_run_keys(redis)
    finally:
        await redis.aclose()


async def clear_run_keys(redis, namespace: str = REDIS_NAMESPACE) -> int:
    """Delete every key owned by one run. Never use flushdb: it is server-wide."""
    deleted = 0
    async for key in redis.scan_iter(match=f"{namespace}:*", count=500):
        deleted += await redis.delete(key)
    return deleted


def _psql(sql: str, db: str | None = None) -> None:
    dsn = SUPER_DSN if db is None else SUPER_DSN.rsplit("/", 1)[0] + f"/{db}"
    subprocess.run(["psql", dsn, "-v", "ON_ERROR_STOP=1", "-q", "-c", sql], check=True)


@pytest.fixture(scope="session", autouse=True)
def database():
    _psql(f'DROP DATABASE IF EXISTS {TEST_DB} WITH (FORCE)')
    # Roles are the one genuinely shared object between concurrent runs: the
    # database is per-run, but nur_admin/nur_app are cluster-wide. Two runs
    # provisioning them at once raced ("tuple concurrently updated"), so the
    # whole role section runs under one advisory lock held for the life of this
    # psql session, and each CREATE tolerates having lost the race.
    _psql(f"""SELECT pg_advisory_lock(hashtext('nur_test_role_provisioning'));
    DO $$ BEGIN
      BEGIN
        CREATE ROLE nur_admin LOGIN CREATEDB NOSUPERUSER NOCREATEROLE;
      EXCEPTION WHEN duplicate_object THEN NULL; END;
      BEGIN
        CREATE ROLE nur_app LOGIN NOSUPERUSER NOCREATEROLE NOCREATEDB NOBYPASSRLS;
      EXCEPTION WHEN duplicate_object THEN NULL; END;
      BEGIN
        CREATE ROLE nur_email_lookup NOLOGIN NOSUPERUSER NOCREATEROLE NOCREATEDB BYPASSRLS;
      EXCEPTION WHEN duplicate_object THEN NULL; END;
    END $$;
    GRANT nur_email_lookup TO nur_admin WITH ADMIN OPTION;
    ALTER ROLE nur_admin PASSWORD '{ADMIN_PW}';
    ALTER ROLE nur_app PASSWORD '{APP_PW}';
    -- nur_admin is the migration role: every FORCE-RLS agentic table applies its
    -- policy to the table owner too, and Alembic never sets app.current_user_id.
    -- Without BYPASSRLS, every migration-time bulk UPDATE (legacy-consent
    -- invalidation, backfills, reconciliation) silently touches zero rows —
    -- confirmed by direct probe against this exact schema. `ALTER ROLE ...
    -- BYPASSRLS` requires actual superuser, unlike CREATEROLE, which is why this
    -- lives in role provisioning and not in a migration.
    ALTER ROLE nur_admin BYPASSRLS;""")
    _psql(f"CREATE DATABASE {TEST_DB} OWNER nur_admin")
    # Embeddings are nullable REAL[] infrastructure in this beta; lexical
    # retrieval is the live path, so tests do not require a pgvector extension.
    _psql("ALTER SCHEMA public OWNER TO nur_admin", db=TEST_DB)
    _psql("GRANT USAGE ON SCHEMA public TO nur_app", db=TEST_DB)
    _psql("GRANT ALL ON SCHEMA public TO nur_email_lookup", db=TEST_DB)
    _psql("GRANT nur_email_lookup TO nur_admin WITH ADMIN OPTION", db=TEST_DB)

    proc = subprocess.run([sys.executable, "-m", "alembic.config", "upgrade", "head"], cwd=API_DIR,
                          capture_output=True, text=True,
                          env={**os.environ, "ALEMBIC_DATABASE_URL": ADMIN_URL})
    assert proc.returncode == 0, f"alembic failed:\n{proc.stdout}\n{proc.stderr}"
    yield
    # Per-run resources: reclaim both so repeated runs accumulate nothing.
    _psql(f"DROP DATABASE IF EXISTS {TEST_DB} WITH (FORCE)")
    asyncio.run(_drop_run_namespace())


@pytest_asyncio.fixture()
async def client():
    from httpx import ASGITransport, AsyncClient
    from redis.asyncio import Redis

    from app.core.config import get_settings
    from app.main import create_app

    get_settings.cache_clear()
    import app.db.session as dbs
    dbs._engine = None
    dbs._sessionmaker = None

    application = create_app()
    application.state.redis = Redis.from_url(os.environ["REDIS_URL"], decode_responses=True)
    # Clear only this run's keys. `flushdb()` would wipe every concurrent run's
    # limiter state as well — the exact corruption this isolation prevents.
    await clear_run_keys(application.state.redis)
    transport = ASGITransport(app=application)
    async with AsyncClient(transport=transport, base_url="http://test") as c:
        c.app = application
        yield c
    await application.state.redis.aclose()
    if dbs._engine is not None:
        await dbs._engine.dispose()


@pytest_asyncio.fixture()
async def super_engine():
    """Superuser engine — bypasses RLS; used ONLY to assert raw persistence."""
    from sqlalchemy.ext.asyncio import create_async_engine
    eng = create_async_engine(SUPER_TEST_URL)
    yield eng
    await eng.dispose()


@pytest_asyncio.fixture()
async def app_engine():
    """Engine as the constrained runtime role, for direct RLS boundary tests."""
    from sqlalchemy.ext.asyncio import create_async_engine
    eng = create_async_engine(APP_URL)
    yield eng
    await eng.dispose()


@pytest_asyncio.fixture()
async def admin_engine():
    """Engine as nur_admin — the role every Alembic migration runs as.

    Distinct from `super_engine`: this proves what a migration can actually see
    and mutate, under the same BYPASSRLS grant migrations get, with no
    `app.current_user_id` ever set.
    """
    from sqlalchemy.ext.asyncio import create_async_engine
    eng = create_async_engine(ADMIN_URL)
    yield eng
    await eng.dispose()


def unique_email() -> str:
    return f"t-{uuid.uuid4().hex[:10]}@nurapp.dev"


async def register_user(client, *, chosen_name="Star", password="orbit-passphrase-9"):
    email = unique_email()
    r = await client.post("/api/v1/auth/register",
                          json={"chosen_name": chosen_name, "email": email,
                                "password": password, "consent": True})
    return r, email, password
